### ISSUE TITLE
Request to Publish Pre-trained Model

### ISSUE THREAD

**Issue by iohara** [razvan05/evaluated_ai_melodies#1]
Hello,

Thank you for sharing this amazing project. I would like to request that you publish the pre-trained model used in this project. Having access to the pre-trained model would greatly benefit those who want to replicate the results and further experiment with the model.

Specifically, could you provide the following files:
- Model weights (my_checkpoint)
- Unique notes file (unique_notes.npy)
- Unique durations file (unique_dur.npy)

Providing these files would be a tremendous help to the community.

Thank you for your consideration!

**Comment by razvan05** [comment]
Hello,

I am sorry for answering after such a long period of time. 
I have added the requested files.
I hope it is not too late for you to use it.

Best regartds!

**Comment by iohara** [comment]
Hello,

Thank you so much for providing the requested files. I greatly appreciate your effort and prompt response, even after some time. These files will be beneficial for my work and for the community.

Best regards!
